services:

  soc-backend:
    build: ../soc_backend
    container_name: soc-backend
    restart: unless-stopped
    volumes:
      - ../soc_backend/data:/app/Private
    networks:
      - soc-network

  soc-menu:
    image: nginx
    container_name: soc-menu
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../soc_frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - soc-backend
    networks:
      - soc-network

networks:
  soc-network: